### ISSUE TITLE
Add tests and implementation for sum<double>

### ISSUE THREAD

**Issue by KevenDenen** [KevenDenen/LinqRebuilt#4]
Add tests and implementation of `Sum<double>` similar to the existing tests and implementation for `Sum<int>`.

**Comment by sotiriszogos** [comment]
@KevenDenen  Hello, I have added the tests for sum<double> in the pull request #7. If you have some time please take a look and merge it if it is fine, in order to create the next pull request for sum<float>. Thank you in advance!

**Comment by KevenDenen** [comment]
The tests added are helpful, but are testing against Linq, not against the Enumerable class in the solutions. It wasn't super clear, so I accepted the pull request, but additional work needs to be done to add the implementation. Reopening.

**Comment by KevenDenen** [comment]
PR #8 solved additional issues. Closing.
