### ISSUE TITLE
Add tests and implementation for sum<float>

### ISSUE THREAD

**Issue by KevenDenen** [KevenDenen/LinqRebuilt#6]
Add tests and implementation for `Sum<float>` similar to what already exists for `Sum<int>`

**Comment by sotiriszogos** [comment]
@KevenDenen Hello, I have also added the implementation and tests for sum float in the pull request #10

**Comment by KevenDenen** [comment]
@sotiriszogos  Awesome, thanks so much for the help! Great job on this one!
